name = "MissileETA"
uid = "2318c9b6-3e0f-47e5-b032-86abbceff14f"
version = 1
copyright = "Don't use it to nuke anybody IRL I guess"
description = "Displays Missile construction ETA"
author = "Pyzu"
url = "https://github.com/Pyzaaa/MissileETAmod"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
